import { StyleSheet } from 'react-native';
import { colors } from '../../styles/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F9FC' },
  content: { padding: 18, paddingBottom: 100 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.white, fontWeight: '800' },
  headerCopy: { flex: 1, marginLeft: 11 },
  eyebrow: { color: colors.muted, fontSize: 12 },
  heading: { color: colors.navy, fontSize: 24, fontWeight: '800' },
  title: { color: colors.navy, fontSize: 18, fontWeight: '800' },
  subtitle: { color: colors.muted, fontSize: 12, marginTop: 3 },
  card: { backgroundColor: colors.white, borderRadius: 14, padding: 15, marginBottom: 12, borderWidth: 1, borderColor: '#E7ECF3' },
  statRow: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  stat: { flex: 1, backgroundColor: colors.white, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#E7ECF3' },
  statValue: { color: colors.navy, fontSize: 20, fontWeight: '800' },
  statLabel: { color: colors.muted, fontSize: 10, marginTop: 4 },
  search: { backgroundColor: colors.white, borderWidth: 1, borderColor: '#DDE4EE', borderRadius: 10, paddingHorizontal: 13, height: 44, marginBottom: 12, color: colors.navy },
  row: { flexDirection: 'row', alignItems: 'center' },
  flex: { flex: 1 },
  studentName: { color: colors.navy, fontWeight: '800', fontSize: 15 },
  muted: { color: colors.muted, fontSize: 12, marginTop: 4 },
  chip: { alignSelf: 'flex-start', borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5, backgroundColor: '#FFF4D8' },
  reviewedChip: { backgroundColor: '#E4F6EC' },
  chipText: { color: '#A46B00', fontSize: 10, fontWeight: '800' },
  reviewedText: { color: '#198754' },
  button: { backgroundColor: colors.blue, borderRadius: 9, paddingVertical: 12, paddingHorizontal: 14, alignItems: 'center', marginTop: 12 },
  buttonText: { color: colors.white, fontWeight: '800', fontSize: 12 },
  secondaryButton: { backgroundColor: '#EAF1FF' },
  secondaryText: { color: colors.blue },
  sectionTitle: { color: colors.navy, fontSize: 15, fontWeight: '800', marginBottom: 10, marginTop: 8 },
  barTrack: { height: 9, borderRadius: 5, backgroundColor: '#E8EDF4', overflow: 'hidden', marginTop: 6, marginBottom: 10 },
  bar: { height: '100%', backgroundColor: colors.blue, borderRadius: 5 },
  pathway: { borderWidth: 1, borderColor: '#DDE4EE', borderRadius: 9, padding: 11, marginBottom: 8 },
  pathwayText: { color: colors.navy, fontWeight: '700' },
  input: { minHeight: 140, borderWidth: 1, borderColor: '#DDE4EE', borderRadius: 10, backgroundColor: colors.white, padding: 12, textAlignVertical: 'top', color: colors.navy },
  bottomTabs: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 68, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: '#E7ECF3', flexDirection: 'row' },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabText: { color: colors.muted, fontSize: 10, marginTop: 4 },
  activeTab: { color: colors.blue, fontWeight: '800' },
  error: { color: '#B42318', backgroundColor: '#FEECEC', padding: 10, borderRadius: 8, marginBottom: 12 },
});

